services:
  db:
    image: postgres:15-alpine
    container_name: sinan-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - sinan_pg_data:/var/lib/postgresql/data
    networks:
      - sinan_net
  pgadmin:
    image: dpage/pgadmin4:7.7
    container_name: sinan-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - sinan_net
  backend:
    container_name: sinan-backend
    build: 
      context: .
      target: builder 
    command: npx tsx watch src/api/index.ts
    volumes:
      - .:/app
      - /app/node_modules 
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    depends_on:
      - db
    networks:
      - sinan_net
volumes:
  sinan_pg_data:

networks:
  sinan_net:
    driver: bridge
