ALTER TABLE "users" ADD COLUMN "public_id" uuid DEFAULT gen_random_uuid() NOT NULL;--> statement-breakpoint
ALTER TABLE "units" ADD COLUMN "public_id" uuid DEFAULT gen_random_uuid() NOT NULL;--> statement-breakpoint
UPDATE "users" SET "public_id" = "id";--> statement-breakpoint
ALTER TABLE "units" ADD CONSTRAINT "units_public_id_unique" UNIQUE ("public_id");--> statement-breakpoint
ALTER TABLE "patients" ADD COLUMN "public_id" uuid DEFAULT gen_random_uuid() NOT NULL;--> statement-breakpoint
UPDATE "patients" SET "public_id" = "id";--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "public_id" uuid DEFAULT gen_random_uuid() NOT NULL;--> statement-breakpoint
UPDATE "notifications" SET "public_id" = "id";--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "id_new" integer GENERATED BY DEFAULT AS IDENTITY;--> statement-breakpoint
ALTER TABLE "patients" ADD COLUMN "id_new" integer GENERATED BY DEFAULT AS IDENTITY;--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "id_new" integer GENERATED BY DEFAULT AS IDENTITY;--> statement-breakpoint
ALTER TABLE "refresh_tokens" ADD COLUMN "id_new" integer GENERATED BY DEFAULT AS IDENTITY;--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "patient_id_new" integer;--> statement-breakpoint
ALTER TABLE "refresh_tokens" ADD COLUMN "user_id_new" integer;--> statement-breakpoint
ALTER TABLE "notifications_botulism" ADD COLUMN "notification_id_new" integer;--> statement-breakpoint
UPDATE "notifications" AS n SET "patient_id_new" = p."id_new" FROM "patients" AS p WHERE p."id" = n."patient_id";--> statement-breakpoint
UPDATE "refresh_tokens" AS r SET "user_id_new" = u."id_new" FROM "users" AS u WHERE u."id" = r."user_id";--> statement-breakpoint
UPDATE "notifications_botulism" AS b SET "notification_id_new" = n."id_new" FROM "notifications" AS n WHERE n."id" = b."notification_id";--> statement-breakpoint
ALTER TABLE "notifications" DROP CONSTRAINT "notifications_patient_id_patients_id_fk";--> statement-breakpoint
ALTER TABLE "refresh_tokens" DROP CONSTRAINT "refresh_tokens_user_id_users_id_fk";--> statement-breakpoint
ALTER TABLE "notifications_botulism" DROP CONSTRAINT "notifications_botulism_notification_id_notifications_id_fk";--> statement-breakpoint
ALTER TABLE "users" DROP CONSTRAINT "users_pkey";--> statement-breakpoint
ALTER TABLE "patients" DROP CONSTRAINT "patients_pkey";--> statement-breakpoint
ALTER TABLE "notifications" DROP CONSTRAINT "notifications_pkey";--> statement-breakpoint
ALTER TABLE "refresh_tokens" DROP CONSTRAINT "refresh_tokens_pkey";--> statement-breakpoint
ALTER TABLE "notifications_botulism" DROP CONSTRAINT "notifications_botulism_pkey";--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "id";--> statement-breakpoint
ALTER TABLE "patients" DROP COLUMN "id";--> statement-breakpoint
ALTER TABLE "notifications" DROP COLUMN "id";--> statement-breakpoint
ALTER TABLE "refresh_tokens" DROP COLUMN "id";--> statement-breakpoint
ALTER TABLE "refresh_tokens" DROP COLUMN "user_id";--> statement-breakpoint
ALTER TABLE "notifications" DROP COLUMN "patient_id";--> statement-breakpoint
ALTER TABLE "notifications_botulism" DROP COLUMN "notification_id";--> statement-breakpoint
ALTER TABLE "users" RENAME COLUMN "id_new" TO "id";--> statement-breakpoint
ALTER TABLE "patients" RENAME COLUMN "id_new" TO "id";--> statement-breakpoint
ALTER TABLE "notifications" RENAME COLUMN "id_new" TO "id";--> statement-breakpoint
ALTER TABLE "refresh_tokens" RENAME COLUMN "id_new" TO "id";--> statement-breakpoint
ALTER TABLE "refresh_tokens" RENAME COLUMN "user_id_new" TO "user_id";--> statement-breakpoint
ALTER TABLE "notifications" RENAME COLUMN "patient_id_new" TO "patient_id";--> statement-breakpoint
ALTER TABLE "notifications_botulism" RENAME COLUMN "notification_id_new" TO "notification_id";--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "patients" ADD CONSTRAINT "patients_pkey" PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "notifications_botulism" ADD CONSTRAINT "notifications_botulism_pkey" PRIMARY KEY ("notification_id");--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_public_id_unique" UNIQUE ("public_id");--> statement-breakpoint
ALTER TABLE "patients" ADD CONSTRAINT "patients_public_id_unique" UNIQUE ("public_id");--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_public_id_unique" UNIQUE ("public_id");--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_patient_id_patients_id_fk" FOREIGN KEY ("patient_id") REFERENCES "public"."patients"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications_botulism" ADD CONSTRAINT "notifications_botulism_notification_id_notifications_id_fk" FOREIGN KEY ("notification_id") REFERENCES "public"."notifications"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "notification_patient_id_index" ON "notifications" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "notifications_botulism_notification_id_idx" ON "notifications_botulism" USING btree ("notification_id");