from app.models import DengueChikungunyaNotification

DENGUE_FIELD_ALIASES = {
    'occupation': ['occupation'],
    'dt_investigation': ['dt_investigation'],
    'st_fever': ['st_fever', 'has_fever'],
    'st_myalgia': ['st_myalgia'],
    'st_headache': ['st_headache'],
    'st_exanthema': ['st_exanthema'],
    'st_vomiting': ['st_vomiting'],
    'st_nausea': ['st_nausea'],
    'st_back_pain': ['st_back_pain'],
    'st_conjunctivitis': ['st_conjunctivitis'],
    'st_arthritis': ['st_arthritis'],
    'st_severe_arthralgia': ['st_severe_arthralgia', 'has_severe_arthralgia'],
    'st_petechiae': ['st_petechiae'],
    'st_leukopenia': ['st_leukopenia'],
    'st_tourniquet_test': ['st_tourniquet_test'],
    'st_retroorbital_pain': ['st_retroorbital_pain'],
    'dt_den_ns1': ['dt_den_ns1'],
    'res_den_ns1': ['res_den_ns1', 'ns1_result'],
    'dt_den_igm': ['dt_den_igm'],
    'res_den_igm': ['res_den_igm'],
    'dt_chik_igm_s1': ['dt_chik_igm_s1'],
    'res_chik_igm_s1': ['res_chik_igm_s1', 'chik_s1_result'],
    'dt_chik_igm_s2': ['dt_chik_igm_s2'],
    'st_hospitalization': ['st_hospitalization'],
    'dt_hospitalization': ['dt_hospitalization'],
    'st_autochthonous': ['st_autochthonous'],
    'tp_final_classification': ['tp_final_classification', 'classification_type'],
    'tp_confirmation_criteria': ['tp_confirmation_criteria'],
    'tp_clinical_presentation': ['tp_clinical_presentation'],
    'tp_evolution': ['tp_evolution'],
    'dt_closing': ['dt_closing'],
    'additional_observations': ['additional_observations'],
    'st_shock': ['st_shock', 'has_shock'],
}

DENGUE_REGISTRY_ENTRIES = {
    'dengue': {
        'storage_slug': 'dengue',
        'specific_model': DengueChikungunyaNotification,
        'field_aliases': DENGUE_FIELD_ALIASES,
    },
    'dengue_chikungunya': {
        'storage_slug': 'dengue_chikungunya',
        'specific_model': DengueChikungunyaNotification,
        'field_aliases': DENGUE_FIELD_ALIASES,
    },
}
